### ISSUE TITLE
how to upload docs when using vercel directly

### ISSUE THREAD

**Issue by tiwentichat** [ClemDev2000/chatdocs#2]
Hi Clem,

this project is wonderful!
I like it so much! but now i have a question: whether I need to upload docs to the root folder or not if I run this repo on vercel directly?

it seems no pdf or txt docs in webapp or root folder

**Comment by tiwentichat** [comment]
I clone, i install, i index, i run, i deploy, then it worked, just in frontend T T
https://chatdocs.i-robot.life ，would you kindly help me to figure out what's wrong? thanks so much!

except the customize svg, other steps are from top to bottom finished
the domain url and exclude is copy to terminal

**Comment by cthiriet** [comment]
Hi @tiwentichat,

Thanks for opening this pull request!

You don't need to upload docs or txt files to the root folder because the indexing part is done by `crawl.py`. It will store the text in your Pinecone vector database for later retrieval.
If you want to query the content of your PDF, audio or video files, I recommend using [fileschat.com](https://fileschat.com/), a product developed by our company.

Feel free to modify the logo svg in `webapp/public/logo.svg` and redeploy the website so that the changes are taken into account.

Thanks! 🙂
